name: Nightly Pull from Salesforce

on:
  schedule:
    - cron: '0 5 * * *'      
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SFDX CLI
        run: npm install -g sfdx-cli

      - name: Authenticate to org
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx_auth.txt
          sfdx force:auth:sfdxurl:store -f sfdx_auth.txt -a devOrg

      - name: Retrieve metadata
        run: sfdx force:source:retrieve -u devOrg -x manifest/package.xml -w 20

      - name: Export Setup Audit Trail
        run: |
          # Export the last 1 day of audit entries in JSON
          sfdx force:data:soql:query \
            -u devOrg \
            -q "SELECT Action, Section, CreatedBy.Name, CreatedDate, Display FROM SetupAuditTrail WHERE CreatedDate = LAST_N_DAYS:1" \
            --json > audit/SetupAuditTrail.json

      - name: Commit & push if anything changed
        run: |
          git config user.name "SF Auto Bot"
          git config user.email "bot@example.com"
          git add -A
          echo "---- after staging ----"
          git status -s || true
          git diff --cached --name-only || true
          if ! git diff --cached --quiet; then
            git commit -m "Nightly auto-pull $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
