name: Nightly Pull from Salesforce

on:
  schedule:
    - cron: '0 5 * * *'      
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SFDX CLI
        run: npm install -g sfdx-cli

      - name: Authenticate to org
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx_auth.txt
          sfdx force:auth:sfdxurl:store -f sfdx_auth.txt -a devOrg
      
      - name: Show which org we authenticated
        run: |
          sfdx force:org:display -u devOrg

      - name: Confirm manifest in repo
        run: |
          ls -l manifest/package.xml
          head -n 40 manifest/package.xml || true

      - name: Sanity retrieve a tiny type
        run: |
          # Replace with something you just edited; CustomLabel is a good smoke test
          sfdx force:source:retrieve -u devOrg -m CustomLabel -w 5 || true

      - name: Show git status/diff BEFORE staging
        run: |
          git status -s || true
          git diff --name-only || true

      - name: Retrieve metadata
        run: sfdx force:source:retrieve -u devOrg -x manifest/package.xml -w 20

      - name: Export Setup Audit Trail
        run: |
          # Export the last 30 days of audit entries in JSON
          sfdx force:data:soql:query \
            -u devOrg \
            -q "SELECT Action, Section, CreatedBy.Name, CreatedDate, Display FROM SetupAuditTrail WHERE CreatedDate = LAST_N_DAYS:1" \
            --json > audit/SetupAuditTrail.json

      - name: Commit & push if anything changed
        run: |
          git config user.email "autobot@example.com"
          git config user.name "SF Auto Bot"
          git add force-app/ audit/SetupAuditTrail.json
          if ! git diff --cached --quiet; then
            git commit -m "Nightly auto-pull $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
